---
- hosts: localhost
  become: no
  gather_facts: no

  pre_tasks:
    - name: Include external vars
      include_vars:
        file: dog_info.yml

  roles:
    - webapp

- hosts: webservers
  become: yes
  gather_facts: no

  roles:
    - name: apache
      when: 'host_service == "apache"'

- hosts: localhost
  become: no
  gather_facts: no

  pre_tasks:
    - shell: whoami
      register: x
    
    - debug:
        var: x

    - name: Include vault
      include_vars:
        file: "{{ firebase_vault }}"
      when: 'host_service == "firebase"'

  roles:
    - name: firebase
      when: 'host_service == "firebase"'