---
- hosts: localhost
  become: no
  gather_facts: no

  pre_tasks:
    - name: Include external vars
      include_vars:
        file: dog_info.yml

  roles:
    - webapp

  tasks:
    - name: Deploy to Apache
      block:
        - include_role:
            name: apache
      become: yes
      delegate_to: "{{ groups['webservers'][0] }}"
      when: 'host_service == "apache"'

    - name: Deploy to Firebase
      include_role:
        name: firebase
      when: 'host_service == "firebase"'

    - name: Deploy to AWS
      include_role:
        name: aws
      when: 'host_service == "aws"'