---
- hosts: localhost
  become: no
  gather_facts: no

  pre_tasks:
    - name: Include external vars
      include_vars:
        file: dog_info.yml

    - name: Include vault
      include_vars:
        file: "{{ firebase_vault }}"
      when: 'host_service == "firebase"'

  roles:
    - name: smoke-test