---
- name: Assert required information provided
  assert:
    that:
      - birth_year|int
      - birth_month|int
      - birth_day|int

- name: Create site directories
  file:
    path: "{{ web_content }}/{{ item }}"
    state: directory
  loop:
    - js
    - css
    - assets

- name: Copy static files
  copy:
    src: "{{ playbook_dir }}/public/{{ item }}"
    dest: "{{ web_content }}/{{ item }}"
  loop:
    - assets/{{ dog_profile_pic }}.png
    - css/main.css
    - js/main.js
  notify: Restart Apache

- name: Copy dynamic files
  template:
    src: "templates/{{ item }}"
    dest: "{{ web_content }}/{{ item | replace('.j2','') }}"
  loop:
    - index.html.j2
    - app.manifest.json.j2
  notify: Restart Apache