---
- name: Assert required information provided
  assert:
    that:
      - birth_year|int
      - birth_month|int
      - birth_day|int

- name: Render templates
  template:
    src: "{{ playbook_dir }}/site/templates/{{ item }}"
    dest: "{{ playbook_dir }}/site/src/{{ item | replace('.j2','') }}"
  loop:
    - index.html.j2
    - app.manifest.json.j2