- name: Assert project defined
  assert:
    that: project_name is defined
    fail_msg: Must define project_name
  when: host_service in project_required

- name: Assert site url provided
  assert:
    that: 'site_url != "UNK"'
    fail_msg: Must define site_url

- name: Get site content
  uri:
    url: "{{ site_url }}"
    method: GET
    return_content: yes
  register: test

- name: Assert content is live
  assert:
    that: 
      - expected_title in test.content
      - expected_img in test.content