- name: Install Firebase CLI
  shell: |
    which firebase > /dev/null 2>&1
    if [[ $? -eq 1 ]]; then
      curl -sL https://firebase.tools | bash
    fi

- name: Set environment token for Firebase CLI to use
  shell: "export FIREBASE_TOKEN={{ firebase_token }}"
  when: firebase_token is defined

- name: Deploy project to Firebase
  shell: "firebase deploy --project {{ firebase_project }}"
  register: deploy_logs

- name: Save deployment logs
  copy:
    content: "{{ deploy_logs }}"
    dest: "{{ playbook_dir }}/firebase-deploy.log.json"